/* Generated by Yosys 0.67+92 (git sha1 30fe16c7f-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

module logic_gate(a, b, sum, big);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [8:0] sum;
  wire [8:0] sum;
  output big;
  wire big;
  wire big_SB_LUT4_O_I2;
  wire big_SB_LUT4_O_I2_SB_CARRY_CO_CI;
  wire big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI;
  wire big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI;
  wire big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI;
  wire [2:0] big_SB_LUT4_O_I3;
  wire [2:0] big_SB_LUT4_O_I3_SB_LUT4_O_I3;
  wire sum_SB_LUT4_O_1_I3;
  wire sum_SB_LUT4_O_2_I3;
  wire sum_SB_LUT4_O_3_I3;
  wire sum_SB_LUT4_O_4_I3;
  wire sum_SB_LUT4_O_5_I3;
  wire sum_SB_LUT4_O_7_I3;
  wire sum_SB_LUT4_O_I3;
  SB_LUT4 #(
    .LUT_INIT(16'hc0f0)
  ) big_SB_LUT4_O (
    .I0(1'h0),
    .I1(sum[8]),
    .I2(big_SB_LUT4_O_I2),
    .I3(big_SB_LUT4_O_I3[2]),
    .O(big)
  );
  SB_CARRY big_SB_LUT4_O_I2_SB_CARRY_CO (
    .CI(big_SB_LUT4_O_I2_SB_CARRY_CO_CI),
    .CO(big_SB_LUT4_O_I2),
    .I0(sum[8]),
    .I1(1'h1)
  );
  SB_CARRY big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO (
    .CI(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .CO(big_SB_LUT4_O_I2_SB_CARRY_CO_CI),
    .I0(sum[7]),
    .I1(1'h0)
  );
  SB_CARRY big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO (
    .CI(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .CO(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .I0(sum[6]),
    .I1(1'h0)
  );
  SB_CARRY big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO (
    .CI(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .CO(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .I0(sum[5]),
    .I1(1'h1)
  );
  SB_CARRY big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO (
    .CI(sum[3]),
    .CO(big_SB_LUT4_O_I2_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI_SB_CARRY_CO_CI),
    .I0(sum[4]),
    .I1(1'h1)
  );
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) big_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(sum[4]),
    .I2(sum[5]),
    .I3(big_SB_LUT4_O_I3_SB_LUT4_O_I3[2]),
    .O(big_SB_LUT4_O_I3[2])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h0003)
  ) big_SB_LUT4_O_I3_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(sum[0]),
    .I2(sum[1]),
    .I3(sum[2]),
    .O(big_SB_LUT4_O_I3_SB_LUT4_O_I3[2])
  );
  SB_CARRY sum_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_7_I3),
    .CO(sum[8]),
    .I0(a[7]),
    .I1(b[7])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O (
    .I0(1'h0),
    .I1(a[4]),
    .I2(b[4]),
    .I3(sum_SB_LUT4_O_I3),
    .O(sum[4])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(a[6]),
    .I2(b[6]),
    .I3(sum_SB_LUT4_O_1_I3),
    .O(sum[6])
  );
  SB_CARRY sum_SB_LUT4_O_1_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_5_I3),
    .CO(sum_SB_LUT4_O_1_I3),
    .I0(a[5]),
    .I1(b[5])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(a[3]),
    .I2(b[3]),
    .I3(sum_SB_LUT4_O_2_I3),
    .O(sum[3])
  );
  SB_CARRY sum_SB_LUT4_O_2_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_4_I3),
    .CO(sum_SB_LUT4_O_2_I3),
    .I0(a[2]),
    .I1(b[2])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(a[1]),
    .I2(b[1]),
    .I3(sum_SB_LUT4_O_3_I3),
    .O(sum[1])
  );
  SB_CARRY sum_SB_LUT4_O_3_I3_SB_CARRY_CO (
    .CI(1'h0),
    .CO(sum_SB_LUT4_O_3_I3),
    .I0(a[0]),
    .I1(b[0])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(a[2]),
    .I2(b[2]),
    .I3(sum_SB_LUT4_O_4_I3),
    .O(sum[2])
  );
  SB_CARRY sum_SB_LUT4_O_4_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_3_I3),
    .CO(sum_SB_LUT4_O_4_I3),
    .I0(a[1]),
    .I1(b[1])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_5 (
    .I0(1'h0),
    .I1(a[5]),
    .I2(b[5]),
    .I3(sum_SB_LUT4_O_5_I3),
    .O(sum[5])
  );
  SB_CARRY sum_SB_LUT4_O_5_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_I3),
    .CO(sum_SB_LUT4_O_5_I3),
    .I0(a[4]),
    .I1(b[4])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_6 (
    .I0(1'h0),
    .I1(a[0]),
    .I2(b[0]),
    .I3(1'h0),
    .O(sum[0])
  );
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) sum_SB_LUT4_O_7 (
    .I0(1'h0),
    .I1(a[7]),
    .I2(b[7]),
    .I3(sum_SB_LUT4_O_7_I3),
    .O(sum[7])
  );
  SB_CARRY sum_SB_LUT4_O_7_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_1_I3),
    .CO(sum_SB_LUT4_O_7_I3),
    .I0(a[6]),
    .I1(b[6])
  );
  SB_CARRY sum_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(sum_SB_LUT4_O_2_I3),
    .CO(sum_SB_LUT4_O_I3),
    .I0(a[3]),
    .I1(b[3])
  );
  assign big_SB_LUT4_O_I3_SB_LUT4_O_I3[1:0] = sum[5:4];
  assign big_SB_LUT4_O_I3[1:0] = { big_SB_LUT4_O_I2, sum[8] };
endmodule
